Traceback (most recent call last):
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Define x and y value ranges
xmin=-2*np.pi; xmax=2*np.pi;
ymin=-2.5; ymax=2.5;

# We will use 10 grid points in each direction
npts=10
x=np.linspace(xmin,xmax,npts)
y=np.linspace(ymin,ymax,npts)
[X,Y]=np.meshgrid(x,y)

# Define the vector field values at each point
(U,V)=(Y,-np.sin(X))

# Make and twiddle the plot
fig,ax=plt.figure(figsize=(12,6))    
plt.title('The simple pendulum with no damping')
ax[0].quiver(X,Y,U,V)
ax[1].streamplot(X,Y,U,V,arrowsize=2)

#ax[0].set_xlabel('x')
#ax[0].set_ylabel('y')

plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32mC:\Users\ELLAME~1\AppData\Local\Temp/ipykernel_6316/566637670.py[0m in [0;36m<module>[1;34m[0m
[0;32m     13[0m [1;33m[0m[0m
[0;32m     14[0m [1;31m# Make and twiddle the plot[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 15[1;33m [0mfig[0m[1;33m,[0m[0max[0m[1;33m=[0m[0mplt[0m[1;33m.[0m[0mfigure[0m[1;33m([0m[0mfigsize[0m[1;33m=[0m[1;33m([0m[1;36m12[0m[1;33m,[0m[1;36m6[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     16[0m [0mplt[0m[1;33m.[0m[0mtitle[0m[1;33m([0m[1;34m'The simple pendulum with no damping'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     17[0m [0max[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m.[0m[0mquiver[0m[1;33m([0m[0mX[0m[1;33m,[0m[0mY[0m[1;33m,[0m[0mU[0m[1;33m,[0m[0mV[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: cannot unpack non-iterable Figure object
TypeError: cannot unpack non-iterable Figure object

